Item:
    Name: example1
    DisplayName: This is an Example Item
    Material: STICK
    Amount: 1
    Lore: This is some lore!!!!
    Glow: true
Item:
    Name: example2
    DisplayName: <&4>Fire Wool
    Material: RED_WOOL
    Amount: 3
    Lore: <&c>This wool belongs to the Fire Nation<n><&c>Use with care!
    Glow: true
    UnshapedRecipe: WHITE_WOOL, RED_WOOL:3, WHITE_WOOL, example1:3
Item:
    Name: example3
    DisplayName: <&2>Earth <&a>Walkers
    Material: GOLDEN_BOOTS
    ShapedRecipe: GOLD_INGOT, AIR, GOLD_INGOT, GOLD_INGOT, DIRT:16, GOLD_INGOT  
    Stats:
        EarthSmashFlightSpeed: 25
        EarthSmashFlightDuration: 25
        EarthSmashDamage: -15
        WearOnly: true
Item:
    Name: example4
    DisplayName: <&4><&l>BLAZE ROD!
    Material: BLAZE_ROD
    UnshapedRecipe: BLAZE_ROD:3, BLAZE_POWDER:3
    Stats:
        Charges: 20
        BlazeArcRange: 30
        BlazeRingRange: 30
        DestroyAfterCharges: true
        RequireElement: fire
        RequireWorld: world
        ParticleEffects: flame:5:100:10:100
Item:
    Name: example5
    DisplayName: <&9>Azula Stone
    Material: REDSTONE
    Lore: <&c>Instantly charges Lightning
    Stats:
        SneakCharges: 1
        DestroyAfterCharges: true
        IgnoreDestroyMessage: true
        AllowFromInventory: true
        LightningChargeTime: -300
        ParticleEffects: magiccrit:15:50:10:0
Item:
    Name: example6
    DisplayName: <&2>Cactus Juice
    Material: POTION
    Lore: <&8>Makes you dizzy but increases <n><&8>your resistance to damage.<n><&8>Octopusform charges faster<n><&8>Airbenders can glide without a glider
    Stats:
        DestroyAfterCharges: true
        IgnoreDestroyMessage: true
        ConsumeEffects: CONFUSION:3:15, DAMAGE_RESISTANCE:2:5, AirGlide:true:15, AirGlideSpeed:50:15, OctopusFormInterval:-100:15
Item:
    Name: example7
    DisplayName: <&b>Water Leggings with Water Pouch
    Material: LEATHER_LEGGINGS
    Lore: <&8>Basic Leggings that come equipped with a Water Pouch.<n><&7>You must double tap your abilities to execute them.
    ShapedRecipe: LEATHER, LEATHER, LEATHER, LEATHER, POTION:1:WATER, LEATHER, LEATHER, POTION:1:WATER, LEATHER
    Glow: true
    Stats:
        Charges: 50
        DestroyAfterCharges: false
        WaterSource: true
Item: 
    Name: glider
    DisplayName: <&f>Airbender Staff
    Lore: <&8>A versatile wooden staff used by <&f><&l>Air Nomads<n><&7>Press sneak while falling to glide<n><&7>Improves the knockback of<n><&f>  AirBlast<n><&f>  AirSwipe<n><&f>  AirSuction
    Material: STICK
    ShapedRecipe: WHITE_WOOL:8, WHITE_WOOL:8, WHITE_WOOL:8, AIR, STICK:8, WHITE_WOOL:8, FEATHER:8, AIR, WHITE_WOOL:8
    Glow: true
    Stats:
        Charges: 50
        DestroyAfterCharges: true
        IgnoreDestroyMessage: false
        AirGlide: true
        AirBlastPushFactor: 20
        AirBlastPushFactorForOthers: 20
        AirSuctionPushFactor: 20
        AirSwipePushFactor: 100
Item: 
    Name: badgermoletunic
    DisplayName: <&3>Badgermole Tunic
    Lore: <&8>The spirit of the badgermole lives on<n><&7>Focus your <&3>EarthTunnel <&7>into a smaller portion<n><&7>of earth, increasing the speed.
    Material: IRON_CHESTPLATE
    UnshapedRecipe: COAL_BLOCK:3, IRON_ORE:3, GOLD_ORE:3, STONE:3, LIME_TERRACOTTA:3, GREEN_TERRACOTTA:3
    Stats:
        WearOnly: true
        SneakCharges: 25
        EarthTunnelMaxRadius: -60
Item: 
    Name: northpolehelmet
    DisplayName: <&b>Arctic Helmet of the North
    Lore: <&8>crafted in the northern water tribe<n><&7>Increases <&b>ice<&7> based abilities by <&e>20%<n><&7>Decreases <&9>water<&7> mobility abilities by <&e>20%.
    Material: LEATHER_HELMET
    ShapedRecipe: ICE:4, ICE:4, ICE:4, ICE:4, LEATHER:16, ICE:4
    Glow: true
    Stats:
        LeatherColor: 85, 255, 255
        WearOnly: true
        IceSpikeRange: 20
        IceBlastRange: 20
        IceBlastDamage: 20
        IceSpikeDamage: 20
        IceSpikePillarRange: 20
        IceSpikePillarDamage: 20
        IceSpikePillarFieldDamage: 20
        SurgeWaveMaxFreezeRadius: 20
        WaterSpoutHeight: -20
        WaterSpoutWaveFlightDuration: -20
        WaterSpoutWaveSpeed: -20
        WaterSpoutWaveRadius: -20
Item:
    Name: flameo
    DisplayName: <&c>Flameo Chef Hat
    Lore: <&8>Buy <&4>'Flameo Instant Noodles!'<n><&8>The Noodliest Noodles in the United Republic!<n><&7>Greatly increases <&c>HeatControl<&7> cooking speed.
    Material: LEATHER_HELMET
    ShapedRecipe: RED_WOOL:1, RED_WOOL:1, RED_WOOL:1, RED_WOOL:1, COAL_BLOCK:3, RED_WOOL:1
    Glow: true
    Stats:
        LeatherColor: 255, 0, 0
        SneakCharges: 15
        DestroyAfterCharges: true
Item:
    Name: waterchestplate
    DisplayName: <&9>Brutal Water Chestplate
    Lore: <&8>The toughest <&b>water<&8> benders <n><&8>specialize in close combat<n><&7>Increases <&9>OctopusForm<&7> by <&e>30%<n><&7>Increases <&9>Torrent<&7> damage by <&e>15%<n><&7>Decreases <&9>Torrent<&7> range by <&e>25%
    Material: LEATHER_CHESTPLATE
    ShapedRecipe: POTION, AIR, POTION, POTION, LEATHER_CHESTPLATE, POTION, POTION, POTION, POTION
    Stats:
        WearOnly: true
        LeatherColor: 85, 85, 255
        Charges: 100
        DestroyAfterCharges:
        OctopusFormRange: 30
        OctopusFormDamage: 30
        OctopusFormKnockback: -50
        OctopusFormRadius: 15
        OctopusFormInterval: 30
        TorrentDamage: 15
        TorrentRange: -25
Item:
    Name: antilag
    DisplayName: <&c>Anti-Lag Machine
    Lore: <&8>Everyone loves you for using this item<n><&7>Decreases the radius of AirBubble<n><&7>and WaterBubble substantially!
    Material: DAYLIGHT_DETECTOR
